### ISSUE TITLE
新增图源（吉林一号MK）

### ISSUE THREAD

**Issue by LreeLenn** [liuxspro/TinyTileProxy#17]
2024年度全国高质量一张图 92e687bbb824b4def35cfab91c9103d0
北京市超清影像(VIP限定) ea08e647fbe4dadff9d05a5d988649b5
2023年度全国高质量一张图 73ad26c4aa6957eef051ecc5a15308b4
2022度全球一张图 2d9bf902749f1630bc25fc720ba7c29f

**Comment by liuxspro** [comment]
#18 现在可以通过在配置文件中的`jl1_mk`节添加自定义mk了

```toml
[jl1_mk]
73ad26c4aa6957eef051ecc5a15308b4 = "2023年度全国高质量一张图"
2d9bf902749f1630bc25fc720ba7c29f = "2022年度全球一张图"
```
